    db:
        container_name: postgresdb
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=ihatejava
            - POSTGRES_USER=humster
            - POSTGRES_DB=humsterbot
            - PGDATA=~/.postgresql/data/pgdata
        ports:
            - 5432:5432
